# This file exists primarily to
# interface with rails, but it doesn't
# hold any actual config data.
#
# In a development environment, env vars
# will be bootstrapped from values in
# config/.env
default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
